In [2]:
# Importing pandas library for data analysis
import pandas as pd

print('Import Setup Done')

Import Setup Done

In [3]:
# Reading CSV file into a DataFrame
# import data from csv files into dataframes and remove the index columns that is auto generated with values on 0-n in rows
# downloaded data from stack overflow survey page: https://survey.stackoverflow.co/
# For example, you can see in this dataset that the CSV file has a built-in index, which pandas did not pick up on automatically. 
# To make pandas use that column for the index (instead of creating a new one from scratch), we can specify an index_col
surveys = pd.read_csv('data/survey_results_public.csv', index_col=0)
print('Loading data!!')

Loading data!!

In [8]:
# Displaying the first 5 rows of the DataFrame
# Display first 5 records in dataframe using head() Pass the numbers of records you want to fetch like head(15)
surveys.head()
# Display last 5 records in dataframe using tail() Pass the numbers of records you want to fetch like tail(15)
surveys.tail()

,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,
65433,I am a developer by profession,18-24 years old,"Employed, full-time",Remote,Apples,Hobby;School or academic work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","On the job training;School (i.e., University, ...",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65434,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65435,I am a developer by profession,25-34 years old,"Employed, full-time",In-person,Apples,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Stack Overflow;Social ...,API document(s) and/or SDK document(s);AI-powe...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65436,I am a developer by profession,18-24 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby;Contribute to open-source projects;Profe...,"Secondary school (e.g. American high school, G...",On the job training;Other online resources (e....,Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
65437,I code primarily as a hobby,18-24 years old,"Student, full-time",NaN,Apples,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
# Checking the number of rows and columns in the DataFrame
# too see the no. of rows and column you can use Shape
surveys.shape

(65437, 113)

In [16]:
# Code cell
# to select any column data we cam directly use surveys.CodingActivities OR surveys['CodingActivities']
# extracting a column from data frame returns a series only
# Datafame is like a table whereas the series is likle an array or list.
activities = surveys.CodingActivities
print(type(activities))

<class 'pandas.core.series.Series'>

In [28]:
# Accessing specific rows or columns using .loc/.iloc
# now in order to access spectific records we use
# df.iloc[0]  only works on the index of the columns not on the names
# df.loc[:,0]
# pandas also uses slicing using : for example select 0-10 records
surveys.iloc[0:10]
# it can use a list or numbers as well which will return thw rows numbered in the list
surveys.iloc[[1,3,5,7,9], 3] # ther is an additional param which can be passed as index of column either 0,1,23

ResponseId
2     Remote
4        NaN
6        NaN
8        NaN
10    Remote
Name: RemoteWork, dtype: object

In [31]:
# Accessing specific rows or columns using .loc/.iloc
# in order to access the records based on the names of cilumns we use
surveys.loc[:10, 'RemoteWork']
# here the first param will the number of records you wanto to access 2nd param will be the name os columns you wnat it could be a list as well
cols = ['CodingActivities', 'EdLevel','LearnCode']
surveys.loc[:10,cols]# get all the records with given cols only again slicing can be done here like we slice in string where right part of slice is not inclued

,CodingActivities,EdLevel,LearnCode
ResponseId,,,
1,Hobby,Primary/elementary school,Books / Physical media
2,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...
3,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...
4,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f..."
5,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f..."
6,NaN,Primary/elementary school,"School (i.e., University, College, etc);Online..."
7,I don’t code outside of work,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Other online resources (e.g., videos, blogs, f..."
8,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f..."
9,Hobby,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Books / Physical media;Other online resources ...
10,Bootstrapping a business,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",On the job training;Other online resources (e....

In [33]:
# Accessing specific rows or columns using .loc/.iloc
# conditional selection 
# we can utilise == (Equal operator) & (AND operator) | (OR operator)
# other operator as well >,<,>=,<=
surveys.loc[surveys.CodingActivities == 'Hobby']
surveys.loc[(surveys.CodingActivities == 'Hobby') & (surveys.RemoteWork == 'Remote') | (surveys.JobSat > 5 )]

# we have other methods as well like
surveys.loc[surveys.CodingActivities.isin(['Hobby', 'I don’t code outside of work'])]

surveys.CodingActivities.notnull()

# we can assign values to existing df like
surveys['CodingActivities'] = 'xyz' # it will alter all the vvalues of CodingActivities to xyz.

,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,I code primarily as a hobby,45-54 years old,"Employed, full-time",In-person,Apples,Hobby,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Books / Physical media;Other online resources ...,Stack Overflow;Written-based Online Courses,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN,NaN
16,I am a developer by profession,45-54 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby,Some college/university study without earning ...,Books / Physical media;On the job training;Oth...,Technical documentation;Books;Written Tutorial...,API document(s) and/or SDK document(s),...,0.0,0.0,0.0,0.0,0.0,0.0,Appropriate in length,Neither easy nor difficult,NaN,5.0
22,I am a developer by profession,35-44 years old,"Employed, full-time",In-person,Apples,Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);Traditi...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
28,I am a developer by profession,25-34 years old,"Employed, full-time;Independent contractor, fr...",Remote,Apples,Hobby,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Books / Physical media;On the job training,NaN,NaN,...,50.0,20.0,15.0,15.0,0.0,0.0,Appropriate in length,Neither easy nor difficult,NaN,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65402,I am a developer by profession,25-34 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;On the job training;Other online res...,Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65409,I am a developer by profession,25-34 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",On the job training;Other online resources (e....,Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65424,I am a developer by profession,18-24 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65425,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Apples,Hobby,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65435,I am a developer by profession,25-34 years old,"Employed, full-time",In-person,Apples,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Stack Overflow;Social ...,API document(s) and/or SDK document(s);AI-powe...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN